import React, { useEffect, useState } from 'react'
import { useLawyerPrep } from '../../hooks/useLawyerPrep'
import {
  Scale,
  Copy,
  Printer,
  Download,
  RefreshCw,
  HelpCircle,
  FileText,
  Check,
  Edit3,
  ExternalLink,
  ShieldCheck,
  Plus,
  Trash2,
  CheckSquare,
  Square
} from 'lucide-react'
import './LawyerPrepTab.css'

export default function LawyerPrepTab({ analyzeResult }) {
  const { result, loading, error, run } = useLawyerPrep()
  const [copied, setCopied] = useState(false)
  const [notes, setNotes] = useState({})
  const [activeNoteId, setActiveNoteId] = useState(null)
  const [selectedQuestions, setSelectedQuestions] = useState({})
  const [customQuestions, setCustomQuestions] = useState([])
  const [newQuestionText, setNewQuestionText] = useState('')
  const [newQuestionReason, setNewQuestionReason] = useState('')
  const [showAddCustom, setShowAddCustom] = useState(false)

  useEffect(() => {
    if (analyzeResult && !result) {
      run(analyzeResult)
    }
  }, [analyzeResult])

  useEffect(() => {
    if (result?.questions) {
      const initial = {}
      result.questions.forEach((_, idx) => {
        initial[idx] = true
      })
      setSelectedQuestions(initial)
    }
  }, [result])

  function toggleQuestion(idx) {
    setSelectedQuestions((prev) => ({
      ...prev,
      [idx]: !prev[idx],
    }))
  }

  function handleSelectAll(val) {
    if (!result?.questions) return
    const updated = {}
    result.questions.forEach((_, idx) => {
      updated[idx] = val
    })
    setSelectedQuestions(updated)
  }

  function handleAddCustomQuestion(e) {
    e.preventDefault()
    if (!newQuestionText.trim()) return
    setCustomQuestions((prev) => [
      ...prev,
      {
        question: newQuestionText.trim(),
        why_it_matters: newQuestionReason.trim() || 'Custom priority issue for your specific contract context.'
      }
    ])
    setNewQuestionText('')
    setNewQuestionReason('')
    setShowAddCustom(false)
  }

  function handleDeleteCustom(idx) {
    setCustomQuestions((prev) => prev.filter((_, i) => i !== idx))
  }

  function getActiveQuestionsForExport() {
    const list = []
    if (result?.questions) {
      result.questions.forEach((q, i) => {
        if (selectedQuestions[i]) {
          list.push({ ...q, note: notes[i], isCustom: false })
        }
      })
    }
    customQuestions.forEach((q, i) => {
      list.push({ ...q, note: notes[`custom-${i}`], isCustom: true })
    })
    return list
  }

  function handleCopy() {
    const active = getActiveQuestionsForExport()
    if (active.length === 0) return

    const text = active
      .map((q, i) => {
        let entry = `${i + 1}. ${q.question}\n   Why it matters: ${q.why_it_matters}`
        if (q.note) {
          entry += `\n   My Consultation Notes: ${q.note}`
        }
        return entry
      })
      .join('\n\n')

    navigator.clipboard.writeText(`ATTORNEY CONSULTATION PREPARATION SHEET\n\n${text}`)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  function handleDownloadBrief() {
    const active = getActiveQuestionsForExport()
    if (active.length === 0) return

    const text = active
      .map((q, i) => {
        let entry = `${i + 1}. ${q.question}\n   Why it matters: ${q.why_it_matters}`
        if (q.note) {
          entry += `\n   My Consultation Notes: ${q.note}`
        }
        return entry
      })
      .join('\n\n')

    const fileContent = `ATTORNEY CONSULTATION PREPARATION SHEET\nGenerated by LegalAssist\nDate: ${new Date().toLocaleDateString()}\n\n` +
      `IMPORTANT NOTICE:\nLegalAssist is an informational clarity tool, not a law firm or licensed attorney. These questions serve as a structured starting point for your consultation.\n\n` +
      `============================================================\n\n${text}\n`

    const blob = new Blob([fileContent], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `attorney-consultation-brief-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  function handlePrint() {
    window.print()
  }

  function handleNoteChange(index, val) {
    setNotes((prev) => ({
      ...prev,
      [index]: val,
    }))
  }

  return (
    <div className="lawyer-prep-tab">
      <div className="lawyer-prep-inner">
        <div className="lawyer-prep-hero card">
          <div className="hero-icon-circle">
            <Scale size={28} />
          </div>
          <div className="hero-content">
            <h1>Attorney Consultation Prep Sheet</h1>
            <p className="hero-desc">
              These customized questions are derived directly from the ambiguities, high-risk terms, and one-sided clauses flagged in your document. Bring this agenda to your attorney consultation to get the most value out of your meeting.
            </p>
          </div>
        </div>

        <div className="lawyer-framing card">
          <div className="framing-header">
            <ShieldCheck size={16} className="framing-icon" />
            <h3>Important Professional Context</h3>
          </div>
          <p>
            LegalAssist is an informational clarity tool, not a law firm or licensed attorney. These questions serve as a structured starting point for your meeting. A licensed lawyer in your jurisdiction is the only professional qualified to evaluate your individual risks and legal strategy.
          </p>
        </div>

        {!analyzeResult && !result && (
          <div className="empty-state card">
            <div className="empty-state-icon-wrap">
              <Scale size={28} />
            </div>
            <h3>No Document Analysis Found</h3>
            <p>
              Run an analysis on a document in the <strong>Analyze tab</strong> first to generate a consultation agenda.
            </p>
          </div>
        )}

        {analyzeResult && loading && (
          <div className="empty-state loading-state card">
            <div className="loading-spinner-wrap">
              <span className="spinner loading-lg" />
            </div>
            <h3>Formulating targeted attorney questions…</h3>
            <p>Synthesizing flagged risks, ambiguous phrasing, and key terms into high-leverage discussion topics.</p>
          </div>
        )}

        {error && <div className="error-message">{error}</div>}

        {result?.questions?.length > 0 && (
          <div className="questions-section animate-fade-in">
            <div className="questions-header-bar">
              <div className="questions-title-group">
                <h2>{result.questions.length} Questions for Your Attorney</h2>
                <span className="questions-badge">Prioritized by Risk</span>
              </div>

              <div className="questions-actions">
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  onClick={handleCopy}
                  title="Copy formatted questions and notes"
                >
                  {copied ? <Check size={13} className="text-success" /> : <Copy size={13} />}
                  <span>{copied ? 'Copied' : 'Copy All'}</span>
                </button>
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  onClick={handleDownloadBrief}
                  title="Download formatted consultation brief as text file"
                >
                  <Download size={13} />
                  <span>Download Brief</span>
                </button>
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  onClick={handlePrint}
                  title="Print consultation sheet"
                >
                  <Printer size={13} />
                  <span>Print Sheet</span>
                </button>
                {analyzeResult && (
                  <button
                    type="button"
                    className="btn btn-ghost btn-sm"
                    onClick={() => run(analyzeResult)}
                    title="Regenerate questions"
                  >
                    <RefreshCw size={13} />
                    <span>Regenerate</span>
                  </button>
                )}
              </div>
            </div>

            {/* Question selection & custom question toolbar */}
            <div className="questions-tracker-bar card">
              <div className="tracker-left">
                <span className="tracker-status">
                  <strong>{getActiveQuestionsForExport().length}</strong> of{' '}
                  {(result?.questions?.length || 0) + customQuestions.length} questions included in agenda
                </span>
                <div className="tracker-select-btns">
                  <button
                    type="button"
                    className="btn btn-ghost btn-xs"
                    onClick={() => handleSelectAll(true)}
                  >
                    Select All
                  </button>
                  <button
                    type="button"
                    className="btn btn-ghost btn-xs"
                    onClick={() => handleSelectAll(false)}
                  >
                    Deselect All
                  </button>
                </div>
              </div>
              <button
                type="button"
                className="btn btn-primary btn-sm add-custom-q-btn"
                onClick={() => setShowAddCustom((s) => !s)}
              >
                <Plus size={14} />
                <span>{showAddCustom ? 'Cancel' : 'Add Custom Question'}</span>
              </button>
            </div>

            {/* Custom Question Form */}
            {showAddCustom && (
              <form onSubmit={handleAddCustomQuestion} className="custom-question-form card animate-fade-in">
                <h4>Add Specific Question for Your Lawyer</h4>
                <div className="form-field">
                  <label htmlFor="custom-q-text">Your Question:</label>
                  <input
                    id="custom-q-text"
                    type="text"
                    placeholder="e.g. Can the landlord deduct normal wear and tear from my security deposit in this state?"
                    value={newQuestionText}
                    onChange={(e) => setNewQuestionText(e.target.value)}
                    required
                  />
                </div>
                <div className="form-field">
                  <label htmlFor="custom-q-reason">Why It Matters to You:</label>
                  <input
                    id="custom-q-reason"
                    type="text"
                    placeholder="e.g. The lease has an aggressive $350 mandatory cleaning fee on move-out."
                    value={newQuestionReason}
                    onChange={(e) => setNewQuestionReason(e.target.value)}
                  />
                </div>
                <div className="form-buttons">
                  <button type="submit" className="btn btn-primary btn-sm">
                    Save to Consultation List
                  </button>
                </div>
              </form>
            )}

            <ol className="questions-list">
              {result.questions.map((q, i) => {
                const isSelected = !!selectedQuestions[i]
                return (
                  <li key={i} className={`question-item card ${isSelected ? 'selected' : 'unselected'}`}>
                    <div className="question-item-top">
                      <button
                        type="button"
                        className="question-checkbox-btn"
                        onClick={() => toggleQuestion(i)}
                        title={isSelected ? 'Remove from consultation brief' : 'Include in consultation brief'}
                        aria-label={isSelected ? `Deselect question ${i + 1}` : `Select question ${i + 1}`}
                      >
                        {isSelected ? (
                          <CheckSquare size={18} className="checkbox-icon checked" />
                        ) : (
                          <Square size={18} className="checkbox-icon" />
                        )}
                      </button>
                      <div className="question-number-wrap">
                        <span className="question-number">{i + 1}</span>
                      </div>
                    </div>

                    <div className="question-content">
                      <p className="question-text">{q.question}</p>

                      <div className="why-matters-box">
                        <span className="why-label">Why this is critical to ask</span>
                        <p>{q.why_it_matters}</p>
                      </div>

                      {/* Interactive meeting note */}
                      <div className="question-notes-section">
                        {activeNoteId === i || notes[i] ? (
                          <div className="notes-editor animate-fade-in">
                            <label className="notes-label" htmlFor={`note-${i}`}>
                              <Edit3 size={12} />
                              <span>Attorney's Advice / Your Notes:</span>
                            </label>
                            <textarea
                              id={`note-${i}`}
                              value={notes[i] || ''}
                              onChange={(e) => handleNoteChange(i, e.target.value)}
                              placeholder="Type notes from your conversation here..."
                              rows={2}
                              className="notes-textarea"
                            />
                          </div>
                        ) : (
                          <button
                            type="button"
                            className="btn btn-ghost btn-sm add-note-btn"
                            onClick={() => setActiveNoteId(i)}
                          >
                            <Edit3 size={12} />
                            <span>+ Add Consultation Note</span>
                          </button>
                        )}
                      </div>
                    </div>
                  </li>
                )
              })}

              {/* Custom questions */}
              {customQuestions.map((q, i) => (
                <li key={`custom-${i}`} className="question-item card custom-question-item selected">
                  <div className="question-item-top">
                    <span className="custom-q-badge">Custom</span>
                    <button
                      type="button"
                      className="btn btn-ghost btn-xs delete-custom-btn"
                      onClick={() => handleDeleteCustom(i)}
                      title="Remove custom question"
                      aria-label="Remove custom question"
                    >
                      <Trash2 size={13} />
                    </button>
                  </div>
                  <div className="question-content">
                    <p className="question-text">{q.question}</p>
                    <div className="why-matters-box">
                      <span className="why-label">Why you added this</span>
                      <p>{q.why_it_matters}</p>
                    </div>
                  </div>
                </li>
              ))}
            </ol>

            <div className="lawyer-resources card">
              <div className="resources-header">
                <HelpCircle size={16} className="resources-icon" />
                <h3>Finding Qualified Legal Help</h3>
              </div>
              <p>
                Many state and local bar associations offer low-cost referral programs, and legal aid societies provide assistance for qualifying tenants, employees, and small business owners. When interviewing attorneys, ask if they provide a free 15-minute consultation to review this agenda.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
